### PR TITLE
Katherine/store setup

### PR DESCRIPTION
**Pull request by katherinek123**
initiated store set up

### CODE REVIEW

**Comment by griffin104** [comment]
The <Provider> should wrap around everything!

**Comment by griffin104** [comment]
Use createStore or configureStore to make it!

**Review by griffin104 — CHANGES_REQUESTED** [review]
The default of the `appReducers.js` (and other reducers) should return `state`

**Review by griffin104 — APPROVED** [review]

**Review by griffin104 — APPROVED** [review]

**Review by THLyon — APPROVED** [review]
Looks great!

**Pull request merged**
